#!/usr/bin/python
# -*- coding: utf-8 -*-

from os import path


class Config(object):
    DEBUG = False
    PORT = 5000
    HOST = '0.0.0.0'
    URL_PREFIX = '/api'
    PROJECT_ROOT = path.abspath(path.dirname(__file__))
    TEMPLATE_FOLDER = path.join(PROJECT_ROOT, 'templates')

    SQLALCHEMY_DATABASE_URI = "sqlite://"
    DATABASE_CONNECT_OPTIONS = {}

    SECURITY_TRACKABLE = True

    # =============================================================================================
    # =  NB! DO NOT CHANGE THIS IF YOU HAVE A RUNNING DATABASE - THIS WILL INVALIDATE ALL LOGIN!  =
    # =============================================================================================
    # Simple 64-bit string generated by os.urandom(8)
    PROJECT_SALT = '\xac\xf9\xc6\x96R\xc0\xa1\x05'


class Development(Config):
    DEBUG = True
    SECRET_KEY = 'development'


class Production(Config):
    DEBUG = False
    TESTING = False
    # =======================================================
    # = NB: USING URANDOM INVALIDATES ALL CURRENT SESSIONS! =
    # =======================================================
    # Generate a new random secret key
    SECRET_KEY = 'g\xae\x924>:\x85\xbf\xeb\x1e\x97)\x0cr\xad\xf4'


class Testing(Config):
    TESTING = True
    SECRET_KEY = 'testing'
